article_homepage:
    path:     /
    defaults: { _controller: ArticleBundle:Article:index }
show_article:
    path:     /article/{slug}
    defaults: { _controller: ArticleBundle:Article:showArticle }
show_category:
  path:     /{slug}
  defaults: { _controller: ArticleBundle:Article:showCategory }
search_ajax:
  path:     /search
  defaults: { _controller: ArticleBundle:Article:search }
contact_us:
  path:     /cotactus
  defaults: { _controller: ArticleBundle:Article:showContactUs }
about_us:
  path:     /about_us
  defaults: { _controller: ArticleBundle:Article:showAboutUs }

