article_homepage:
    path:     /home
    defaults: { _controller: ArticleBundle:Article:index }
show_article:
    path:     /article/{id}
    defaults: { _controller: ArticleBundle:Article:showArticle }
