<?php

namespace ArticleBundle\Repository;

/**
 * ImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findImagesByArticle($id)
    {
        $q=$this->getEntityManager()->createQuery('select i FROM  ArticleBundle:Images i
where i.article = :id ')->setParameter('id' , $id);
        return $q->getResult();
    }
}
